name: Save Project

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save
        run: |
          echo "Workflow is working"
